notifications:
  email: false
git:
  depth: 2
  quiet: true
language: java
jdk: openjdk8
rvm: 2.6.4
before_install:
  - chmod +x mvnw
install: true
stages:
  - test
  - deploy
#services:
#  - docker
jobs:
  include:

    - stage: test
      jdk: openjdk8
      name: run mvc test
      script: ./mvnw clean package -pl :mvc

    - stage: test
      jdk: openjdk8
      name: run webflux test
      script: ./mvnw clean package -pl :webflux

    - stage: test
      jdk: openjdk8
      name: run r2dbc test
      before_script:
        - ./mvnw -f r2dbc/app
        - ./mvnw -f r2dbc/postgres/pom.xml docker-compose:up
        - ./mvnw -f r2dbc/app process-resources flyway:migrate
      script: ./mvnw -f r2dbc/app -Ptest
      after_script: ./mvnw -f r2dbc/postgres/pom.xml docker-compose:down

cache:
  packages: true
  directories:
    - ~/.docker
    - ~/.m2
